### ISSUE TITLE
Practica 3 Mockup

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-team-noble#2]
[Practica 3 de Mockup.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-team-noble/files/8497842/Practica.3.de.Mockup.pdf)

https://www.figma.com/file/biBimdBt3ATVa625ubck5j/Prototipo?node-id=0%3A1

**Comment by Abraham890** [comment]
Calificación: 20 Puntos

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/163258273-7adda8c0-cb41-4a20-a1f8-b30a64ea6701.png)
Para aplicar la descentralización, se debe utilizar un inicio de sesión con Near para mayor seguridad, no se puede utilizar google, ni facebook...

**Comment by josealfredo79** [comment]
Aqui esta un ejemplo de un inicio de sesion con near
![image](https://user-images.githubusercontent.com/58342642/163258558-2209df69-c6b3-42b2-8711-4d43e7ae0ac5.png)
https://learnnear.club/
Se debe hacer el cambio para tomar en cuenta la practica por favor...

**Comment by uzias10** [comment]
Ese cambio ya se había realizado la vez que nos hizo la observación en la escuela , pero no se si ya lo pueda visualizar usted. Porque a mi equipo nos aparece como la ilustración que se muestra a continuación... 
![image](https://user-images.githubusercontent.com/79929354/163617016-72a01327-92df-4729-8368-a6d1c32c35d2.png)

**Comment by uzias10** [comment]
Ya se realizaron los cambios permitentes al documento... si lo pudiese revisar de nuevo.

**Comment by josealfredo79** [comment]
Esta bien hecho...
